### ISSUE TITLE
Mobs (villagers and cows) disappears and reappears in my world. 

### ISSUE THREAD

**Issue by R0G3R-R0G3R** [intergrav/Additive#12]
Hi i have some issues with the additive modpack. My cows for example will go over walk trough the  fences visially but when i punch them they teleport back to the "farm". My villagers also keeps disappearing and reappearing in my iron farm. 
I have seen the problems multible times and can get a screenshot of them if needed.
Best regards Erik

**Comment by HyperSoop** [comment]
This might be a problem with entity tracking, try setting `use_optimized_entity_tracking=true` in `config/vmp.properties`

**Comment by R0G3R-R0G3R** [comment]
Sorry im not very good with that sort of stuff, how do i do that?

**Comment by intergrav** [comment]
In your launcher (I assume you are using Prism or MultiMC), select your instance:

![image](https://user-images.githubusercontent.com/42325132/224569928-c34079a5-ba3a-46a1-9890-e6624b604dc8.png)

Click "Folder" on the right side:

![image](https://user-images.githubusercontent.com/42325132/224569939-85685901-131f-4e1e-a9ef-662acdc1ec2a.png)

Open `.minecraft`, then open the `config` folder, and then edit the `vmp.properties` file as shown in HyperSoop's message.

**Comment by R0G3R-R0G3R** [comment]
Thank you soo much, both of you. Hope you both have a great day.
