### ISSUE TITLE
my instance wont load

### ISSUE THREAD

**Issue by TlMEL0RD** [intergrav/Additive#14]

**Comment by intergrav** [comment]
I need much more information to help you:

1. What operating system?
2. What modpack version?
3. Which Minecraft version?
4. Which launcher?
5. Have you made any modifications other than Additive itself?

**Comment by HyperSoop** [comment]
> I need much more information to help you:
> 
> 1. What operating system? (linux distro, mac, or windows)
> 2. What modpack version?
> 3. Which Minecraft version?
> 4. Which launcher?
> 5. Have you made any modifications other than Additive itself?

The best thing would be to ask for logs first and foremost.

**Comment by intergrav** [comment]
Yes, that aswell

**Comment by intergrav** [comment]
Will be closing this as it was very vague and I haven't gotten a response
