### ISSUE TITLE
Crash when selecting CIT Resewn in mod menu

### ISSUE THREAD

**Issue by ASOwnerYT** [intergrav/Additive#15]
Launcher: Prism Launcher (latest version installed via Flatpak)
Modpack version: 1.15.7+1.19.4.quilt
OS: Nobara Linux 37
Logs: https://mclo.gs/kmiCLZW

Only additional mods I installed were No Chat Reports and Shared Resources. This only happens when I select and click the CIT Resewn mod in the mod menu.
![image](https://user-images.githubusercontent.com/23545044/233524160-bf2ba6d5-43ec-4f51-bd38-82729e000439.png)

**Comment by intergrav** [comment]
Looking into it soon. Thanks for the report

**Comment by intergrav** [comment]
The problem seems to be fixed when I add Cloth Config API to the modlist - If I can, I'll publish a patch for this tonight or get one out tomorrow. Thanks once again :)

*Honestly not sure why cloth config isn't marked as an optional dependency for CIT Resewn, imo it should be*

**Comment by intergrav** [comment]
Fixed in https://github.com/intergrav/Additive/commit/196331919b5e03e2228f500a251a607dae90e983 (1.15.8)
