### ISSUE TITLE
Typo in description.

### ISSUE THREAD

**Issue by Lengy2** [intergrav/Additive#16]
In the description there is a typo "*As of 1.15.5, most packs should load properly." there is no "1.15.5" I assume you meant 1.16.5 just letting you know.

**Comment by osfanbuff63** [comment]
This probably isn't a typo - it's probably referring to the modpack version 1.15.5

**Comment by intergrav** [comment]
^^^ yeah, i was referring to the modpack version since 1.15.5 contained Iris 1.6 improving compatibility a ton

**Comment by Lengy2** [comment]
Oh sorry I thought it meant Minecraft 1.15.5 not the modpack version
