### ISSUE TITLE
Mod request: Fix Keyboard on Linux

### ISSUE THREAD

**Issue by MenacingPerson** [intergrav/additive#20]
https://modrinth.com/mod/fix-keyboard-on-linux

It fixes issues that are annoying on Linux. Please add this, it could be nice.

Made by the same guy as c2me and vmp

**Comment by intergrav** [comment]
sure! I'll also consider [EmuNO](https://modrinth.com/mod/emuno) along with this as that disables a few MacOS features that interfere with the game

**Comment by MenacingPerson** [comment]
I think you forgot to add this last release?

**Comment by intergrav** [comment]
i did again 🤦

**Comment by intergrav** [comment]
Added in 1.17.3... sorry for missing it so many times 🤦🏽
