### ISSUE TITLE
smooth boot doesnt need to be added in 1.20.1 

### ISSUE THREAD

**Issue by CrystalClear51** [intergrav/additive#27]
according to the creator of smooth boot, "Smooth Boot is no longer needed since version 1.19.4!
Because Minecraft has fixed this problem itself."

**Comment by intergrav** [comment]
While the main function of smooth boot has been solved by Mojang, the mod still allows you to adjust thread priorities which can improve performance for some. Check out the issue tracker on smooth boot.
