### ISSUE TITLE
Ears

### ISSUE THREAD

**Issue by intergrav** [intergrav/additive#29]
Small, very lightweight mod that adds some optional skin features. Supports many versions of Minecraft and doesn't add any UI or anything (Ears data is stored by pixels in the skin file) so I feel that it's a good fit

https://modrinth.com/mod/ears

**Comment by MenacingPerson** [comment]
Does it work with cosmetica/figura?

**Comment by intergrav** [comment]
It should definitely work with Cosmetica. I asked about Figura on their Discord server and they said that it should be compatible for the most part assume a person is using customizations from one or the other

**Comment by MenacingPerson** [comment]
I tested cosmetica and it definitely works. Thanks!
