### ISSUE TITLE
ModernFix

### ISSUE THREAD

**Issue by Aquoo** [intergrav/additive#30]
ModernFix is a performance mod which reduces startup time and improves memory usage.

https://modrinth.com/mod/modernfix

**Comment by intergrav** [comment]
This mod has been considered in the past, however it's optimizations can be quite intrusive and it provides a very minimal improvement on small packs. It mainly affects configurations that have large amounts of mods. 
If ModernFix becomes in a state where it improves performance a lot - feel free to reopen this issue!
I'll also transfer this over to the Adrenaline issue tracker as this is more suitable for that project.
