### ISSUE TITLE
Add NoChatReports

### ISSUE THREAD

**Issue by kostek0020** [intergrav/additive#32]
Add small mod that strips cryptographic signatures that since 1.19 are attached to every message sent in the chat.

Link: https://modrinth.com/mod/no-chat-reports

**Comment by intergrav** [comment]
No Chat Reports has been considered in the past, however chat reporting is a topic with very mixed opinions. The mod itself is pretty bloated too. There is a config file in Additive that makes the mod less obtrusive, but the mod is not included by default. You may add it manually if you wish, and it will be pre-configured for you.

**Comment by Xplodin** [comment]
> No Chat Reports has been considered in the past, however chat reporting is a topic with very mixed opinions. The mod itself is pretty bloated too. There is a config file in Additive that makes the mod less obtrusive, but the mod is not included by default. You may add it manually if you wish, and it will be pre-configured for you.

Mixed is very off. 
Anyone FOR chat reporting is a useless loser who abuses chat reports to get people banned for fun.
Chat reporting is a very abusive mechanic designed against server owners and people like me who dont want to get banned from others abusing it. There is tons of proof of this being abused and do not trust anything mojang says on the matter as its all lies

**Comment by MenacingPerson** [comment]
Again, just install it yourself.

I use NCR too, but I don't ask a modpack creator to add it after they already say no

**Comment by intergrav** [comment]
Either way, it will not be added. I'm against chat reporting in quite a few ways, but NCR is **not** in the scope of Additive. Additive is an OptiFine alternative, it is not meant to change what Mojang wants to enforce as per their own rules. As always, you can add the mod manually - it only takes a few seconds.
