### ISSUE TITLE
Zoomify keybind conflict

### ISSUE THREAD

**Issue by Uranite** [intergrav/additive#33]
On a fresh new install, zoomify keybind has a conflict with creative mode save hotbar activator, rendering you unable to zoom
Additive version: 1.18.2+1.20.1.fabric
![2023-08-05_13 05 07](https://github.com/intergrav/additive/assets/62639703/f33aa553-dba5-43ef-bfe5-5fef475dc6c6)
![2023-08-05_13 05 02](https://github.com/intergrav/additive/assets/62639703/7a238437-c3fb-4388-a27f-e978aee83f27)

**Comment by intergrav** [comment]
This is intentional behavior as I don't really want to overwrite the save hotbar activator. OptiFine does the same thing. Any ideas to do a workaround for this would be appreciated :)

**Comment by Uranite** [comment]
Might be better to leave it as is since the keybind conflict notification will pop up at boot, users can go and change the keybind themself.
An alternative would be to use a mod like Keybind Fix so that conflicting keybind will still work, and the usage of the save hotbar activator is C + 1, and such anyway so it wont cause unintended behaviour with zoomify, but the mod will cause unintended behaviour if users adds another mod that has a conflicting keybind, I think the solution to this would be for Keybind Fix dev to implement a feature where it will only work for certain keybind only

**Comment by Gaming32** [comment]
Some zoom mods use V as a zoom key, so you could do that. I personally prefer V instead of C for zoom.

**Comment by badooga** [comment]
> Some zoom mods use V as a zoom key, so you could do that. I personally prefer V instead of C for zoom.

V is used by default to access the settings of the very popular Simple Voice Chat mod/plugin, so I dont think that would work well as an Additive default. I personally use C when I play, but if I had to choose a default Zoom keybind for Additive, it'd be Z or X.

**Comment by intergrav** [comment]
I think I'll just stick with what we have currently - Zoomify notifies the user at the beginning anyways :> 
I'd rather not have to change a keybind for this, OptiFine does the same thing (unless it changed, I haven't installed OptiFine in almost a year)
