### ISSUE TITLE
(1.13.1+1.18.2.fabric) Adding mod "Create Fabric" causes a small rendering glitch

### ISSUE THREAD

**Issue by kbsmilk** [intergrav/Additive#9]
I understand this isn't really your problem, but just in case you have any advice...

Found this while building a modpack out of Additive. Vanilla Chest and Bell blocks have an effect that looks like z-fighting, or like lighting going nuts, but only while their animations are *not* playing, and only while the player camera moves.
It is possible that other vanilla blocks have this glitch.
Create Fabric's blocks do not have rendering problems.
Graphics settings were not changed from defaults, excepting GUI scale.

Same issue happens on Adrenaline 1.12.1. Tested with mod lists consisting strictly of your modpacks + Create Fabric 0.5.0.i-921 and its dependencies.
A debug chat message in game warned me to install Indium and that did not help.

**Comment by kbsmilk** [comment]
Hah well I found the problem and solution in Create Fabric's issues. I hope this post helps someone else, anyway.
Create's Flywheel rendering duplicates the rendering of Enhanced Block Entities, specifically on Chests and Bells. Turning them off in EBE settings corrects the problem.
https://github.com/Fabricators-of-Create/Create/issues/316

**Comment by intergrav** [comment]
Sorry I didn't see this earlier, good that you found the issue :)
